server:
  port: 8072

eureka:
    client:
        fetchRegistry: true
        registerWithEureka: true
        serviceUrl:
            defaultZone: http://localhost:8070/eureka/
    instance:
        preferIpAddress: true

spring:
  appliction:
    name: gateway-service
  cloud:
    gateway:
        discovery.locator:
          enabled: true
          lowerCaseServiceId: true
