eureka:
    client:
        fetchRegistry: true
        registerWithEureka: true
        serviceUrl:
            defaultZone: http://localhost:8070/eureka/
    instance:
        preferIpAddress: true


spring:
    datasource:
        password: '{cipher}380ff7249b33df83dc575e8e6a3f029d3739c6e038ff6dd450528fb046f317a3dc6cbb7f954201c5da202b4de4af11c2'
        url: jdbc:postgresql://localhost:5432/danielctrenado
        username: danielctrenado
    jpa:
        properties:
            hibernate:
                default_schema: danschema

management:
  endpoints:
    web:
      exposure:
        include: *

example:
    property: I AM DEV
